### ISSUE TITLE
Really trippy rendering error with mesa on linux

### ISSUE THREAD

**Issue by JopStro** [BruceKnowsHow/Octray#3]
![2020-10-09_23 29 27](https://user-images.githubusercontent.com/33031853/95637060-b2692f80-0a88-11eb-9808-43e01fd25540.png)
I don't think it's supposed to look like this.
I'm using an AMD radeon rx 590 if that helps

**Comment by Fercraft64** [comment]
I have the same problem, but in my case I'm using Windows 10 and a Nivdia GTX1060 graphics card

**Comment by RYRY1002** [comment]
That's strange, first things first: 
1. Make sure you are using Minecraft 1.12.2
2. Try resetting all of Optifine's settings _(you can do this by going into your .minecraft folder and deleting optionsof.txt and optionsshaders.txt)_
If that doesn't help, make sure you have the latest drivers for your graphics card, and you are using the latest version of Optifine (for 1.12.2 its F5)

Hope this helps you out

**Comment by Lucky4Luuk** [comment]
Same problem here, on windows 10, with a gtx1080

**Comment by Fallen4Eyes** [comment]
I also have a similar problem 
Heres a detailed report of the error

# Hardware/Software
Minecraft Version 1.12.2
Optifine version 1.12.2_HD_U_F5

Kernel: 5.10.2-2-MANJARO
CPU: AMD Ryzen 7 2700x
GPU: AMD ATI Radion Vega 64
GPU Kernel driver: amdgpu
Java version 1.8.0_265
OpenGL: 4.6

Full log from screenshot
https://pastebin.com/CiR7Zjcn

![2021-01-08_21 28 47](https://user-images.githubusercontent.com/68693503/104082094-d4de2680-51f8-11eb-83f6-08e934c872d8.png)



An interesting section of the log that might help

[21:26:56] [Server thread/INFO] [minecraft/MinecraftServer]: Fallen_4Eyes joined the game
[21:26:57] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[21:26:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'octray'/overworld
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] countInstances: 1
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow map distance: 232.0
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow map resolution: 8192
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow distance render mul: 2.0
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow map interval size: 1.0E-6
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/shadow
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/gbuffers_basic
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/gbuffers_textured
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/gbuffers_skybasic
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/gbuffers_skytextured
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/gbuffers_water
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex2 mipmap enabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex0 format: RGBA32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex1 format: RGBA32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex2 format: RGBA32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex3 format: RGB32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex4 format: RGBA32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex5 format: RGBA32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex6 format: RGBA32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex7 format: RGBA32F
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex0 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex1 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex2 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex3 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex4 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex5 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex6 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex7 clear disabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Sun path rotation: -40.0
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Noise texture enabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Noise texture resolution: 64
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow map distance: 232.0
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow map resolution: 8192
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow distance render mul: 2.0
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow map interval size: 1.0E-6
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite2
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite3
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite4
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite5
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite6
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite7
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] colortex5 mipmap enabled
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Program loaded: world0/composite8
[21:26:57] [Client thread/ERROR] [net.optifine.shaders.SMCLog]: [Shaders] Couldn't read /shaders/world0/final.fsh!
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: java.io.IOException: Included file not found: /shaders/world0/../programs/composite/Final.glsl
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.optifine.shaders.config.ShaderPackParser.resolveIncludes(ShaderPackParser.java:693)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.optifine.shaders.config.ShaderPackParser.loadFile(ShaderPackParser.java:793)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.optifine.shaders.config.ShaderPackParser.resolveIncludes(ShaderPackParser.java:690)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.optifine.shaders.Shaders.createFragShader(Shaders.java:2916)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.optifine.shaders.Shaders.setupProgram(Shaders.java:2599)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.optifine.shaders.Shaders.init(Shaders.java:2343)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4083)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1593)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:26:57] [Client thread/INFO] [STDERR]: [net.optifine.shaders.Shaders:createFragShader:3211]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] usedColorBuffers: 6
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] usedDepthBuffers: 1
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] usedShadowColorBuffers: 1
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] usedShadowDepthBuffers: 1
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] usedColorAttachs: 6
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] usedDrawBuffers: 4
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Framebuffer created.
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Shadow framebuffer created.
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Reset model renderers
[21:26:57] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Reset world renderers
[21:26:59] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[21:26:59] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'octray'/overworld

**Comment by RYRY1002** [comment]
Seems like final.glsl has an error in the code. I would suggest re-downloading the shader and making sure you are using the latest version of Optifine for 1.12.2

**Comment by rhjdvsgsgks** [comment]
many file system under linux is case sensitive, a typo caused this problem, after a rename #6 it works.

**Comment by trudruchocolatemilk** [comment]
> 
> 
> Seems like final.glsl has an error in the code. I would suggest re-downloading the shader and making sure you are using the latest version of Optifine for 1.12.2

Octray was actually designed on 1.15.2 not 1.12.2 so i would suggest trying it in 1.15.2

**Comment by RYRY1002** [comment]
> Octray was actually designed on 1.15.2 not 1.12.2 so i would suggest trying it in 1.15.2

_cough_ no it was made for 1.12.2 _cough_
If you guys are having any issues with Octray, please use 1.12.2 and see if they still persist.
1.12.2 is a base version of sorts, as it was developed on 1.12.2, and as its still an experimental shader, Bruce cannot guarantee that it will work at all outside of 1.12.2
